CREATE TABLE IF NOT EXISTS gitlab_project (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS github_repo (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gitlab_merge_request (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    gitlab_project_id BIGINT NOT NULL REFERENCES gitlab_project(id),
    gitlab_mr_iid BIGINT NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS github_pull_request (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    github_repo_id BIGINT NOT NULL REFERENCES github_repo(id),
    github_pr_id BIGINT NOT NULL,
    gitlab_merge_request_id BIGINT REFERENCES gitlab_merge_request(id),
    status TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);