// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GithubPullRequest struct {
	ID                   int64
	GithubRepoID         int64
	GithubPrID           int64
	GitlabMergeRequestID pgtype.Int8
	Status               string
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
}

type GithubRepo struct {
	ID          int64
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type GitlabMergeRequest struct {
	ID              int64
	GitlabProjectID int64
	GitlabMrIid     int64
	Status          string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type GitlabProject struct {
	ID          int64
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
