// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GitlabMergeRequest struct {
	ID               int64
	MigrationID      int64
	MrIid            int64
	MergeCommitSha   string
	Parent1CommitSha string
	Parent2CommitSha string
	PrID             int64
	Status           string
	Notes            string
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type GitlabToGithubMigration struct {
	ID                int64
	GitlabProjectName string
	GithubRepoName    string
	Status            string
	Notes             string
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}
